name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Deploy to GitHub Pages
        env:
          PERSONAL_TOKEN: ${{ secrets.tokenPersonal }}
        run: |
          git remote set-url origin https://${PERSONAL_TOKEN}@github.com/${{ github.repository }}.git
          mkdocs gh-deploy --force

